questions = {
    1: {"question": "Zu welcher Konfession gehörst du?", "type": "buttons", "options": ["Evangelisch/Reformiert", "Katholisch", "Konfessionslos/Andere"]},
    2: {"question": "Bist du im Steuerjahr umgezogen?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 5}},
    3: {"question": "Alte Adresse?", "type": "text"},
    4: {"question": "Wohnhaft bis?", "type": "date"},
    5: {"question": "Was ist dein Zivilstand?", "type": "buttons", "options": ["Verheiratet", "eingetragene Partnerschaft", "Verwitwet", "Geschieden"], "skip_if": {"Verwitwet": 8, "Geschieden": 8}},
    6: {"question": "Name Ehepartner/Partner", "type": "text"},
    7: {"question": "Geburtsdatum Ehepartner/Partner", "type": "date"},
    8: {"question": "Hast du Kinder?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 14}},
    9: {"question": "Namen", "type": "text"},
    10: {"question": "Geburtsdatum", "type": "date"},
    11: {"question": "In deinem Haushalt lebend?", "type": "buttons", "options": ["Ja", "Nein"]},
    12: {"question": "Wird das Kind fremd betreut?", "type": "buttons", "options": ["Ja", "Nein"]},
    13: {"question": "Elterliche Vorsorge (Gemeinsam, getrennt)", "type": "buttons", "options": ["Ja", "Nein"]},
    14: {"question": "Unterstützt du Personen (ohne Ehegatten und Kinder) finanziell?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 20}},
    15: {"question": "Name", "type": "text"},
    16: {"question": "Geburtsdatum", "type": "date"},
    17: {"question": "Adresse", "type": "text"},
    18: {"question": "In deinem Haushalt lebend?", "type": "buttons", "options": ["Ja", "Nein"]},
    19: {"question": "Betrag", "type": "text"},
    20: {"question": "Bist du Angestellt oder Selbständig oder im Studium?", "type": "buttons", "options": ["Angestellt", "Studium", "Selbständig"], "skip_if": {"Studium": 25, "Selbständig": 25}, "requires_document": True},
    21: {"question": "Bei wie vielen Arbeitgebern warst du?", "type": "text"},
    22: {"question": "Wie viel Prozent", "type": "text"},
    23: {"question": "Von wann bis wann", "type": "text"},
    24: {"question": "Berufsbezeichnung", "type": "text"},
    25: {"question": "Hast du einen Nebenerwerb?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 28}, "requires_document": True},
    26: {"question": "Bist du Angestellt oder Selbständig?", "type": "buttons", "options": ["Angestellt", "Selbständig"]},
    27: {"question": "Angaben dazu", "type": "text"},
    28: {"question": "Hast du Einkünfte aus Sozial- und anderen Versicherungen erhalten?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 33}, "requires_document": True},
    29: {"question": "AHV/IV Renten & Pensionskassenrenten", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    30: {"question": "Arbeitslosengeld", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    31: {"question": "Krankentaggeld/Unfalltaggeld", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    32: {"question": "EO-Entschädigungen", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    33: {"question": "Hast du im Steuerjahr eine Schenkung oder Erbvorbezug erhalten?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 36}, "requires_document": True},
    34: {"question": "Grösser als 10'000 CHF", "type": "buttons", "options": ["Ja", "Nein"]},
    35: {"question": "Name, Wohnort und Verwandschaftsgrad", "type": "text"},
    36: {"question": "Hast du im Steuerjahr eine Erbschaft erhalten?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 38}, "requires_document": True},
    37: {"question": "Name, Wohnort und Todestag des Erblassers, Datum der Erbteilung, Verwandschaftsgrad", "type": "text"},
    38: {"question": "Bist du an einer unverteilten Erbschaft beteiligt?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 40}, "requires_document": True},
    39: {"question": "Name, Wohnort und Todestag des Erblassers, Verwandschaftsgrad", "type": "text"},
    40: {"question": "Hast du Unterhaltsbeiträge für dich oder deine Kinder erhalten?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    41: {"question": "Hast du Kapitalabfinden anstelle von wiederkehrenden Leistungen erhalten?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    42: {"question": "Besitzt du eine Liegenschaft?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 46}, "requires_document": True},
    43: {"question": "Hast du darauf eine Hypothek?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    44: {"question": "Hast du die Liegenschaft ganz oder Teilweise vermietet?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 46}},
    45: {"question": "Wie viel Prozent der Wohnfläche wurde vermietet?", "type": "text"},
    46: {"question": "Wie gehst du zur Arbeit?", "type": "text"},
    47: {"question": "Adresse deines Arbeitsortes", "type": "text"},
    48: {"question": "Hat dein Arbeitgeber eine Kantine?", "type": "buttons", "options": ["Ja", "Nein"]},
    49: {"question": "Hast du im Homeoffice gearbeitet?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 51}},
    50: {"question": "Wie viele Tage in der Woche?", "type": "text"},
    51: {"question": "Hattest du sonstige Ausgaben um deinen Beruf auszuüben (Berufskleider etc.)?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    52: {"question": "Hast du Schulden? (Ohne Leasing und ohne Hypothek)", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    53: {"question": "Hast du Unterhaltsbeiträge für deinen Partner oder deine Kinder bezahlt?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 55}, "requires_document": True},
    54: {"question": "Betrag", "type": "text"},
    55: {"question": "Hast du in die Vorsorge (Säule 3a, 2. Säule) einbezahlt?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    56: {"question": "Hast du eine Weiterbildung oder Studium absolviert?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 59}, "requires_document": True},
    57: {"question": "Wer hat die Weiterbildung/das Studium bezahlt", "type": "buttons", "options": ["Ich", "Arbeitgeber"]},
    58: {"question": "Wie viel bezahlst du an die Weiterbildung?", "type": "text"},
    59: {"question": "Hattest du Krankheitskosten- und Unfallkosten (Zahnarzt, Brille, Arztrechnungen)?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    60: {"question": "Hast du einer politischen Partei oder sonstige Institutionen gespendet?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    61: {"question": "Hast du Bank-/ Postkonten?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    62: {"question": "Besitzt du Wertschriften (Aktien, Obligationen, Kryptowährungen)?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    63: {"question": "Bist du ein Inhaber einer Firma?", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 66}, "requires_document": True},
    64: {"question": "Wie gross ist dein Anteil am Grundkapital (Stammkapital, Aktienkapital)?", "type": "text"},
    65: {"question": "Hältst du diese Anteile Privat oder im Geschäftsvermögen?", "type": "buttons", "options": ["Privat", "Geschäft"]},
    66: {"question": "Besitz du ein Auto oder Motorrad? Wenn ja, wie viele? (nicht geleast)", "type": "buttons", "options": ["Ja", "Nein"], "skip_if": {"Nein": 70}},
    67: {"question": "Marke", "type": "text"},
    68: {"question": "Neuwert", "type": "text"},
    69: {"question": "Jahrgang", "type": "date"},
    70: {"question": "Hast du eine Lebens- und Rentenversicherung abgeschlossen?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    71: {"question": "Hast du sonstige Vermögenswerte, welche zu versteuern sind (Gold, Silber, Bargeld oder andere Edelmetalle)?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
    72: {"question": "Haben Sie bisher nicht versteuertes Einkommen und Vermögen, das Sie zur Nachbesteuerung anmelden möchten?", "type": "buttons", "options": ["Ja", "Nein"], "requires_document": True},
}
