"""initial schema

Revision ID: 27245029ea06
Revises: 
Create Date: 2026-08-11 21:40:14.624340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27245029ea06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_slots', sa.Integer(), nullable=False),
    sa.Column('slot_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('user', 'advisor', 'admin', name='user_roles'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('retail', sa.Boolean(), nullable=False),
    sa.Column('institutional', sa.Boolean(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('contact_option', sa.String(length=50), nullable=True),
    sa.Column('notify_status_changes', sa.Boolean(), nullable=True),
    sa.Column('notify_new_requests', sa.Boolean(), nullable=True),
    sa.Column('notify_deadline', sa.Boolean(), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('advisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('quote_status', sa.Enum('Pending', 'In Review', 'Accepted', 'Rejected', 'Draft Tax Return in Review', 'Tax Return Approved', name='quote_status'), nullable=True),
    sa.Column('quote_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('final_submitted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_on', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('accepted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tax_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('checklist_completed', sa.Boolean(), nullable=True),
    sa.Column('uploaded_documents', sa.Boolean(), nullable=True),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('final_submitted', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('draft_tax_return_submitted', sa.Boolean(), nullable=False),
    sa.Column('draft_tax_return_approved', sa.Boolean(), nullable=False),
    sa.Column('final_tax_return_submitted', sa.Boolean(), nullable=False),
    sa.Column('draft_file_path', sa.String(length=255), nullable=True),
    sa.Column('final_file_path', sa.String(length=255), nullable=True),
    sa.Column('additional_documents_request', sa.Boolean(), nullable=True),
    sa.Column('additional_documents_uploaded', sa.Boolean(), nullable=True),
    sa.Column('documents_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxable_assets', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_taxes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tax_year_id', sa.Integer(), nullable=False),
    sa.Column('request_text', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.Column('downloaded_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tax_year_id'], ['tax_years.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_year_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tax_year_id'], ['tax_years.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tax_year_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.Column('downloaded_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tax_year_id'], ['tax_years.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('required_document')
    op.drop_table('checklist_answers')
    op.drop_table('additional_document_requests')
    op.drop_table('user_statistics')
    op.drop_table('team_members')
    op.drop_table('tax_years')
    op.drop_table('tax_returns')
    op.drop_table('subscriptions')
    op.drop_table('quotes')
    op.drop_table('invoices')
    op.drop_table('feedback')
    op.drop_table('advisor')
    op.drop_table('user')
    op.drop_table('plans')
    # ### end Alembic commands ###
