"""add assigned_on + rejection reason/comment columns

Revision ID: 5e495435c2ea
Revises: d33115c4acd4
Create Date: 2026-08-12 22:44:12.608815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e495435c2ea'
down_revision = 'd33115c4acd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('tax_years', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('draft_rejection_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_years', schema=None) as batch_op:
        batch_op.drop_column('draft_rejection_comment')
        batch_op.drop_column('assigned_on')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
