"""reminders + deadline extensions

Revision ID: 8c4bf7543916
Revises: 5e495435c2ea
Create Date: 2026-08-12 23:37:52.680802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4bf7543916'
down_revision = '5e495435c2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_year_extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_year_id', sa.Integer(), nullable=False),
    sa.Column('previous_deadline', sa.Date(), nullable=True),
    sa.Column('new_deadline', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tax_year_id'], ['tax_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_years', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_years', schema=None) as batch_op:
        batch_op.drop_column('last_reminded_at')

    op.drop_table('tax_year_extensions')
    # ### end Alembic commands ###
